### ISSUE TITLE
 Visual Studio Extension Bundle not working on VS2019

### ISSUE THREAD

**Issue by vlellouche** [FireflyMigration/MultiProject#7]
Link of the download : https://marketplace.visualstudio.com/items?itemName=Firefly-Migration.VisualStudioExtensionBundle

After downloading the file VSIXBundler.Package.vsix, it's not possible to select VS2019 
 

![2019-04-07_13h27_54](https://user-images.githubusercontent.com/24289222/55682366-3645d700-593b-11e9-869a-c619bd3316d9.png)

**Comment by michaelm7456** [comment]
I've raised a Pull Request [here](https://github.com/FireflyMigration/MultiProject/pull/8) with some changes to allow the Extension to work with Visual Studio 2019.



Hope this helps!

**Comment by noam-honig** [comment]
Hi Michaelm we have a version that is compatible with 2019 at:
https://github.com/FireflyMigration/MultiProject2019

**Comment by michaelm7456** [comment]
Hi noam-honig, 

I've marked my Pull Request as closed, since you've confirmed there is a VS 2019 compatible version of this Extension.

Many thanks!
